name: bitapp_http_x
description: A starting point for Dart libraries or applications.
version: 1.0.7
repository: https://github.com/openbitapp/http_x-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webfeed: ^0.7.0
  http: ^0.13.3
  logger: ^1.1.0
  bitapp_functional_dart: ^1.0.0
  bitapp_isolates: ^1.0.0
  bitapp_cache: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
