name: bitapp_http_x
description: A simple http library
version: 1.0.10
repository: https://github.com/openbitapp/http_x-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  logger: ^1.1.0
  bitapp_functional_dart: ^1.0.0
  bitapp_isolates: ^1.0.1
  bitapp_cache: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
