name: http_x
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  webfeed: ^0.7.0
  http: ^0.13.3
  gl_functional:
    path: ../gl_functional-flutter
  isolates:
    path: ../isolates-flutter

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
